language: node_js
node_js:
  - lts/*
install:
  - yarn
script:
  - yarn build
deploy:
  provider: pages:git
  edge: true
  cleanup: true
  keep_history: true
  repo: Maorey/Maorey.github.io
  token: $DEPLOY_TOKEN
  target_branch: deploy
  local_dir: docs/.vitepress/dist
  on:
    branch: master
